name: Deploy to server
on: push

jobs:
  first_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Hola mundo
        run: echo "Hola mundo"
  second_jobs:
  #needs para que se haga en secuencias
    needs: first_jobs
    runs-on: ubuntu-latest
    steps:
      - name: Hola mundo
        run: echo "Hola mundo"
