name: Pruebas Automáticas

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      #configuracion de de la carpeta appp dentro de la mauina ubuntu 
      
      - name: creacion archivo ubuntu
        run: |
          echo pwd
          echo "Archivo creado en Ubuntu" > ubuntu_file.txt
          echo "Archivo creado en Ubuntu" > appp|ubuntu_file.txt